apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: end-to-end-test-app-3
  title: end-to-end-test-app-3
  publishedAt: "2024-09-18 01:05:01"
  description: 'end-to-end-test-app-3 Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
  tags:
    - rest
    - java
    - openapi
spec:
  type: openapi
  lifecycle: production
  owner: consumer
  definition: |-
    openapi: 3.0.0
    info:
        description: 'end-to-end-test-app-3 Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
        version: 1.0.2
        title: end-to-end-test-app-3
        termsOfService: http://swagger.io/terms/
        contact:
            email: apiteam@swagger.io
        license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
    tags:
        - name: spec
          description: Health
          externalDocs:
            description: Find out more
            url: http://swagger.io
    paths:
        /actuator/health:
            get:
                tags:
                    - spec
                description: Health
                operationId: health
                responses:
                    '200':
                        description: successful operation
                        content:
                            application/json:
                                schema:
                                    type: array
                                    items:
                                        $ref: '#/components/schemas/Health'
                    '404':
                        description: health not found
    servers:
        - url: https://petstore.swagger.io/v2
    components:
        schemas:
            Health:
                type: object
                properties:
                    status:
                        type: string
                        example: UP
